### ISSUE TITLE
Default path has leaked into intellij

### ISSUE THREAD

**Issue by robincafolla** [DanielRamosAcosta/rustier#2]
I'm not sure if it was intentional or not, but this path has leaked into the rustier default settings in intellij

https://github.com/DanielRamosAcosta/rustier/blob/0019782ecc3d4d966c854c3c5b6a3ae2317cf527/src/main/kotlin/com/github/danielramosacosta/rustier/RustfmtStateService.kt#L21

Screen shot taken yesterday in intellij on my pc

![rustier-settings](https://user-images.githubusercontent.com/1263427/100901002-52f13400-34bb-11eb-969e-20071f4002fc.png)

**Comment by DanielRamosAcosta** [comment]
@robincafolla we've stopped the develpment of this plugin, I have to place a note in the Readme, but right now you can use the `Languages & Frameworks/Rust/Rustfmt` option of Intellij
