### ISSUE TITLE
Incompatible with IntelliJ IDEA CE 

### ISSUE THREAD

**Issue by nhooey** [DanielRamosAcosta/rustier#3]
The `rustier` plugin is incompatible with the latest version of IntelliJ IDEA CE:

```
IntelliJ IDEA 2020.3.1 (Community Edition)
Build #IC-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1996M
Cores: 4
```
Here's what the plugin page says:
![image](https://user-images.githubusercontent.com/65458/105647681-48c53380-5e75-11eb-84a3-610ae49f24bb.png)

**Comment by DanielRamosAcosta** [comment]
@nhooey we've stopped the develpment of this plugin, I have to place a note in the Readme, but right now you can use the Languages & Frameworks/Rust/Rustfmt option of Intellij
